---
- name: Create directory
  file:
    path: "{{ runner_dir }}"
    state: directory
    mode: 0755
    owner: "{{ runner_user }}"
    # group: "{{ runner_user }}"
  tags:
    - install

- name: Find the latest runner version (RUN ONCE)
  uri:
    url: "https://api.github.com/repos/{{ runner_download_repository }}/releases/latest"
    headers:
      Content-Type: "application/json"
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  check_mode: false
  register: api_response
  run_once: yes
  become: false
  delegate_to: localhost
  when: runner_version == "latest"
  tags:
    - install

- name: Set runner_version variable (if it is latest)
  set_fact:
    runner_version: "{{ api_response.json.tag_name | regex_replace('^v', '') }}"
  when: runner_version == "latest"

- name: Show the runner_version
  debug:
    msg: "runner_version: {{ runner_version }}"

- name: Check if desired version already installed
  command: "grep -i {{ runner_version }} {{ runner_dir }}/bin/Runner.Listener.deps.json"
  register: runner_installed
  check_mode: false
  changed_when: False
  ignore_errors: yes
  tags:
    - install

- name: Create temporary directory for archive
  file:
    path: "{{ runner_pkg_tempdir }}"
    state: directory
    recurse: yes
    mode: 0777
  run_once: yes
  delegate_to: localhost
  become: false
  when: runner_version not in runner_installed.stdout
  tags:
    - install

- name: Download runner package version - "{{ runner_version }}" (RUN ONCE)
  get_url:
    url:
      "https://github.com/{{ runner_download_repository }}/releases/download/v{{ runner_version }}/\
      actions-runner-linux-{{ github_actions_architecture }}-{{ runner_version }}.tar.gz"
    dest: "{{ runner_pkg_tempdir }}/actions-runner-linux-{{ runner_version }}.tar.gz"
    force: no
  run_once: yes
  become: false
  delegate_to: localhost
  when: runner_version not in runner_installed.stdout or reinstall_runner
  tags:
    - install

- name: Unarchive package
  unarchive:
    src: "{{ runner_pkg_tempdir }}/actions-runner-linux-{{ runner_version }}.tar.gz"
    dest: "{{ runner_dir }}/"
    owner: "{{ runner_user }}"
    mode: 0755
  when: runner_version not in runner_installed.stdout or reinstall_runner
  tags:
    - install

- name: Configure custom env file if required
  blockinfile:
    path: "{{ runner_dir }}/.env"
    block: "{{ custom_env }}"
    owner: "{{ runner_user }}"
    create: yes
    mode: 0755
    marker_begin: "# BEGIN ANSIBLE MANAGED BLOCK"
    marker_end: "# END ANSIBLE MANAGED BLOCK"
  when: custom_env is defined

- set_fact: 
    skip_registration: runner_name in registered_runners.json.runners|map(attribute='name')|list and not use_runner_token
  when: not use_runner_token

- set_fact: 
    registration_token: _registration_token.json.token
  when: not use_runner_token

- name: Register runner (if new installation) for repo
  command:
    "{{ runner_dir }}/./config.sh --url {{ github_url }}/{{ github_owner | default(github_account) }}/{{ github_repo }} \
    --token {{ registration_token }} --name {{ runner_name }} --labels {{ runner_labels | join(',') }} --unattended \
    {{ runner_extra_config_args }}"
  args:
    chdir: "{{ runner_dir }}"
  become: yes
  become_user: "{{ runner_user }}"
  no_log: "{{ hide_sensitive_logs | bool }}"
  when: not skip_registration and not runner_org
  tags:
    - install

- name: Register runner (if new installation) for organization
  command:
    "{{ runner_dir }}/./config.sh --url {{ github_url }}/{{ github_owner | default(github_account) }} \
    --token {{ registration_token }} --name {{ runner_name }} --labels {{ runner_labels | join(',') }} --unattended"
  args:
    chdir: "{{ runner_dir }}"
  become: yes
  become_user: "{{ runner_user }}"
  no_log: "{{ hide_sensitive_logs | bool }}"
  when: not skip_registration and runner_org
  tags:
    - install

- name: Replace registered runner for repo
  command:
    "{{ runner_dir }}/config.sh --url {{ github_url }}/{{ github_owner | default(github_account) }}/{{ github_repo }} \
    --token {{ registration_token }} --name {{ runner_name }} --labels {{ runner_labels | join(',') }} --unattended --replace"
  args:
    chdir: "{{ runner_dir }}"
  become: yes
  become_user: "{{ runner_user }}"
  no_log: "{{ hide_sensitive_logs | bool }}"
  when: skip_registration and reinstall_runner and not runner_org
  tags:
    - install

- name: Replace registered runner for organization
  command:
    "{{ runner_dir }}/config.sh --url {{ github_url }}/{{ github_owner | default(github_account) }} \
    --token {{ registration_token }} --name {{ runner_name }} --labels {{ runner_labels | join(',') }} --unattended --replace"
  args:
    chdir: "{{ runner_dir }}"
  become: yes
  become_user: "{{ runner_user }}"
  no_log: "{{ hide_sensitive_logs | bool }}"
  when: skip_registration and reinstall_runner and runner_org
  tags:
    - install

- name: Install service
  command: "./svc.sh install {{ runner_user }}"
  args:
    chdir: "{{ runner_dir }}"
  when: runner_service not in services
  tags:
    - install

- name: START and enable Github Actions Runner service
  systemd:
    name: "{{ runner_service }}"
    state: started
    enabled: yes
  ignore_errors: "{{ ansible_check_mode }}"
  when: runner_state|lower == "started"
  tags:
    - install

- name: STOP and disable Github Actions Runner service
  systemd:
    name: "{{ runner_service }}"
    state: stopped
    enabled: no
  ignore_errors: "{{ ansible_check_mode }}"
  when: runner_state|lower == "stopped"
  tags:
    - install
